'use strict'

// tests for getOneTimeEvent
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin')
const expect = mochaPlugin.chai.expect
let wrappedGet = mochaPlugin.getWrapper('getOneTimeEvent', './../../oneTimeEvents/get.js', 'main')
let wrappedCreate = mochaPlugin.getWrapper('createOneTimeEvent', './../../oneTimeEvents/create.js', 'main')
let wrappedDelete = mochaPlugin.getWrapper('deleteOneTimeEvent', './../../oneTimeEvents/delete.js', 'main')
let wrappedAddApplicant = mochaPlugin.getWrapper('addApplicantOneTimeEvent', './../../oneTimeEvents/addApplicant.js', 'main')

describe('Applicant OneTimeEvent', () => {
  let HashKey
  let RangeKey
  it('Create OneTimeEvent', () => {
    return wrappedCreate.run({
      requestContext: {
        authorizer: {
          claims: {
            sub: 'USER-SUB-1234'
          }
        }
      },
      body: '{"EventStartDateTime":"2017-08-2 18:30", "Title":"Testing Event", "Description":"Testing Event!", "GeoPointHash":"11111111"}'
    }).then((response) => {
      const body = JSON.parse(response.body)
      HashKey = body.HashKey
      RangeKey = body.RangeKey
      expect(response).to.not.be.empty
      expect(response.statusCode).to.equal(200)
      expect(body.Title).to.equal('Testing Event')
      // console.log('Response: ' + JSON.stringify(response, null, 4))
    })
  })

  it('Read OneTimeEvent: 0 applicant', () => {
    return wrappedGet.run({
      pathParameters: {
        id: HashKey + '&' + RangeKey
      }
    }).then((response) => {
      //console.log('Response: ' + JSON.stringify(response, null, 4))
      const body = JSON.parse(response.body)
      expect(response).to.not.be.empty
      expect(response.statusCode).to.equal(200)
      expect(body.Applicants.length).to.equal(0)
    })
  })

  it('Add Applicant OneTimeEvent', () => {
    return wrappedAddApplicant.run({
      pathParameters: {
        id: HashKey + '&' + RangeKey
      },
      requestContext: {
        authorizer: {
          claims: {
            sub: 'USER-SUB-1234'
          }
        }
      }
    }).then((response) => {
      expect(response).to.not.be.empty
      expect(response.statusCode).to.equal(200)
    })
  })

  it('Read OneTimeEvent: 1 applicant', () => {
    return wrappedGet.run({
      pathParameters: {
        id: HashKey + '&' + RangeKey
      }
    }).then((response) => {
      //console.log('Response: ' + JSON.stringify(response, null, 4))
      const body = JSON.parse(response.body)
      expect(response).to.not.be.empty
      expect(response.statusCode).to.equal(200)
      expect(body.Applicants.length).to.equal(1)
    })
  })

  it('Delete OneTimeEvent', () => {
    return wrappedDelete.run({
      pathParameters: {
        id: HashKey + '&' + RangeKey
      },
      requestContext: {
        authorizer: {
          claims: {
            sub: 'USER-SUB-1234'
          }
        }
      }
    }).then((response) => {
      expect(response).to.not.be.empty
      expect(response.statusCode).to.equal(200)
    })
  })

})
