'use strict'

// tests for getOneTimeEvent
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin')
const expect = mochaPlugin.chai.expect
let wrappedCreate = mochaPlugin.getWrapper('createOneTimeEvent', './../../oneTimeEvents/create.js', 'main')
let wrappedList = mochaPlugin.getWrapper('listOneTimeEvent', './../../oneTimeEvents/list.js', 'main')
let wrappedDelete = mochaPlugin.getWrapper('deleteOneTimeEvent', './../../oneTimeEvents/delete.js', 'main')

describe('List OneTimeEvent', () => {
  let HashKey
  let RangeKey1
  let RangeKey2

  it('Create OneTimeEvent', () => {
    return wrappedCreate.run({
      requestContext: {
        authorizer: {
          claims: {
            sub: 'USER-SUB-1234'
          }
        }
      },
      body: '{"EventStartDateTime":"2017-08-2 18:30", "Title":"Testing Event", "Description":"Testing Event!", "GeoPointHash":"11111129"}'
    }).then((response) => {
      const body = JSON.parse(response.body)
      HashKey = body.HashKey
      RangeKey1 = body.RangeKey
      expect(response).to.not.be.empty
      expect(response.statusCode).to.equal(200)
      expect(body.Title).to.equal('Testing Event')
      // console.log('Response: ' + JSON.stringify(response, null, 4))
    })
  })

  it('Create Another OneTimeEvent', () => {
    return wrappedCreate.run({
      requestContext: {
        authorizer: {
          claims: {
            sub: 'USER-SUB-1234'
          }
        }
      },
      body: '{"EventStartDateTime":"2017-08-2 18:30", "Title":"Testing Event", "Description":"Testing Event!", "GeoPointHash":"11111129"}'
    }).then((response) => {
      const body = JSON.parse(response.body)
      RangeKey2 = body.RangeKey
      expect(response).to.not.be.empty
      expect(response.statusCode).to.equal(200)
      expect(body.Title).to.equal('Testing Event')
      // console.log('Response: ' + JSON.stringify(response, null, 4))
    })
  })

  it('Query both events', () => {
    return wrappedList.run({
      pathParameters: {
        id: HashKey
      }
    }).then((response) => {
      //console.log('Response: ' + JSON.stringify(response, null, 4))
      const body = JSON.parse(response.body)
      expect(response).to.not.be.empty
      expect(response.statusCode).to.equal(200)
      expect(body.length).to.equal(2)
    })
  })

  it('Delete First OneTimeEvent', () => {
    return wrappedDelete.run({
      pathParameters: {
        id: HashKey + '&' + RangeKey1
      },
      requestContext: {
        authorizer: {
          claims: {
            sub: 'USER-SUB-1234'
          }
        }
      }
    }).then((response) => {
      expect(response).to.not.be.empty
      expect(response.statusCode).to.equal(200)
    })
  })

  it('Delete Second OneTimeEvent', () => {
    return wrappedDelete.run({
      pathParameters: {
        id: HashKey + '&' + RangeKey2
      },
      requestContext: {
        authorizer: {
          claims: {
            sub: 'USER-SUB-1234'
          }
        }
      }
    }).then((response) => {
      expect(response).to.not.be.empty
      expect(response.statusCode).to.equal(200)
    })
  })

  it('Query both events after deletion', () => {
    return wrappedList.run({
      pathParameters: {
        id: HashKey
      }
    }).then((response) => {
      //console.log('Response: ' + JSON.stringify(response, null, 4))
      const body = JSON.parse(response.body)
      expect(response).to.not.be.empty
      expect(response.statusCode).to.equal(200)
      expect(body.length).to.equal(0)
    })
  })


})
