service: lambda-backend

plugins:
  - serverless-webpack
  - serverless-mocha-plugin

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs8.9
  stage: prod
  region: us-west-2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  createUser:
    handler: users/create.main
    events:
      - http:
          path: users
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-west-2:297507385750:userpool/us-west-2_coHVEsjMm
  getUser:
    handler: users/get.main
    events:
      - http:
          path: users/{id}
          method: get
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-west-2:297507385750:userpool/us-west-2_coHVEsjMm
  updateUser:
    handler: users/update.main
    events:
      - http:
          path: users/{id}
          method: put
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-west-2:297507385750:userpool/us-west-2_coHVEsjMm
  deleteUser:
    handler: users/delete.main
    events:
      - http:
          path: users/{id}
          method: delete
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-west-2:297507385750:userpool/us-west-2_coHVEsjMm
  createOneTimeEvent:
    handler: oneTimeEvents/create.main
    events:
      - http:
          path: oneTimeEvents
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-west-2:297507385750:userpool/us-west-2_coHVEsjMm
  getOneTimeEvent:
    handler: oneTimeEvents/get.main
    events:
      - http:
          path: oneTimeEvents/{id}
          method: get
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-west-2:297507385750:userpool/us-west-2_coHVEsjMm
  updateOneTimeEvent:
    handler: oneTimeEvents/update.main
    events:
      - http:
          path: oneTimeEvents/{id}
          method: put
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-west-2:297507385750:userpool/us-west-2_coHVEsjMm
  deleteOneTimeEvent:
    handler: oneTimeEvents/delete.main
    events:
      - http:
          path: oneTimeEvents/{id}
          method: delete
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-west-2:297507385750:userpool/us-west-2_coHVEsjMm
  listOneTimeEvent:
    handler: oneTimeEvents/list.main
    events:
      - http:
          path: oneTimeEvents
          method: get
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-west-2:297507385750:userpool/us-west-2_coHVEsjMm
  addApplicant:
    handler: oneTimeEvents/addApplicant.main
    events:
      - http:
          path: oneTimeEvents/{id}/applicants
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-west-2:297507385750:userpool/us-west-2_coHVEsjMm
